create table if not exists public.metric_aggregates (
    id bigint generated by default as identity primary key,
    metric_name varchar(255) not null,
    metric_type varchar(20) not null
        check (metric_type in ('GAUGE', 'COUNTER', 'HISTOGRAM')),
    tag_combination varchar(4000) not null,
    tags_json varchar(4000) not null,
    bucket_time bigint not null check (bucket_time >= 0),
    sample_count bigint not null check (sample_count > 0),
    value_sum double precision not null,
    latest_value double precision not null,
    p50 double precision,
    p95 double precision,
    p99 double precision
);

create index if not exists idx_metric_aggregates_name_time
    on public.metric_aggregates (metric_name, bucket_time);

comment on table public.metric_aggregates is
    'Time-windowed metric aggregates persisted by the MiniDog ingestion service.';
